import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AsideComp from "./components/Aside";
import NavBar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar/>
        <AsideComp/>
        <div className="mt-10 ml-12">
        {children}
        </div>
        </body>
    </html>
  );
}
